import type { VaultConfig } from "../config/types";
import type { VaultFiles } from "./generateVaultFiles";
import { WORKFLOW_PACK_DEFS } from "../config/catalog";

export interface VaultManifest {
  folderCount: number;
  fileCount: number;
  templateCount: number;
  sampleNoteCount: number;
  onboardingDocCount: number;
  basesDocCount: number;
  hasHome: boolean;
  hasGitignore: boolean;
  workflowPackLabels: string[];
}

const ONBOARDING_DOCS = [
  "START HERE.md",
  "First 7 Days.md",
  "Vault Map.md",
  "How to Use This Vault.md",
];

const ROOT_DOCS = new Set([
  "README.md",
  "CLAUDE.md",
  ".gitignore",
  "Home.md",
  "VAULT MANIFEST.md",
  ...ONBOARDING_DOCS,
]);

/**
 * Compute vault stats from already-generated VaultFiles.
 * Pass the result of generateVaultFiles() — no circular dependency.
 */
export function generateManifest(config: VaultConfig, vaultFiles: VaultFiles): VaultManifest {
  const { folders, files } = vaultFiles;
  const allPaths = Object.keys(files);

  const templatePaths = allPaths.filter((p) => p.startsWith("Templates/"));
  const basesPaths = allPaths.filter((p) => p.startsWith("Bases/"));

  const sampleNotes = allPaths.filter((p) => {
    if (ROOT_DOCS.has(p)) return false;
    if (p.startsWith("Templates/")) return false;
    if (p.startsWith(".obsidian/")) return false;
    if (p.startsWith("Bases/")) return false;
    return true;
  });

  const packLabels = config.workflowPacks.map(
    (p) => WORKFLOW_PACK_DEFS.find((d) => d.key === p)?.label ?? p,
  );

  return {
    folderCount: folders.length,
    fileCount: allPaths.length,
    templateCount: templatePaths.length,
    sampleNoteCount: sampleNotes.length,
    onboardingDocCount: ONBOARDING_DOCS.filter((d) => allPaths.includes(d)).length,
    basesDocCount: basesPaths.length,
    hasHome: allPaths.includes("Home.md"),
    hasGitignore: allPaths.includes(".gitignore"),
    workflowPackLabels: packLabels,
  };
}

export function generateManifestMd(manifest: VaultManifest, config: VaultConfig): string {
  const lines = [
    `# VAULT MANIFEST — ${config.vaultName}`,
    "",
    `Generated by [Vault Configurator](https://github.com/krzysiekmtk/vault-configurator).`,
    "",
    "## Summary",
    "",
    `| Item | Count |`,
    `|------|-------|`,
    `| Folders | ${manifest.folderCount} |`,
    `| Files | ${manifest.fileCount} |`,
    `| Templates | ${manifest.templateCount} |`,
    `| Sample notes | ${manifest.sampleNoteCount} |`,
    `| Onboarding docs | ${manifest.onboardingDocCount} |`,
    `| Bases docs | ${manifest.basesDocCount} |`,
    "",
    "## Included",
    "",
    `- Home dashboard: ${manifest.hasHome ? "yes" : "no"}`,
    `- Git ignore: ${manifest.hasGitignore ? "yes" : "no"}`,
  ];

  if (manifest.workflowPackLabels.length) {
    lines.push("", "## Workflow packs", "");
    for (const label of manifest.workflowPackLabels) {
      lines.push(`- ${label}`);
    }
  }

  return lines.join("\n") + "\n";
}
